### ISSUE TITLE
_repo.GetCount<Entity> Giving "System.NullReferenceException: 'Object reference not set to an instance of an object.'"

### ISSUE THREAD

**Issue by ALrehailiAbdulrahman** [sheryever/simple-access-orm#14]
I have entity using SQL view , when calling _repo.GetCount<entity> throwing error "System.NullReferenceException: 'Object reference not set to an instance of an object.'"

`var isExist = _repo.GetCount<AspNetUserRoles>(f => f.UserId == user.Id && f.RoleId == role.Id) > 0;`

**Comment by sheryever** [comment]
The Logger was not created which cause "System.NullReferenceException: 'Object reference not set to an instance of an object.'"

The issue is fixed
