### ISSUE TITLE
SQL scripts

### ISSUE THREAD

**Issue by yelkarama** [sheryever/simple-access-orm#8]
Hi

Can you please share scripts for test databases? 

Thanks

**Comment by sheryever** [comment]
Which Database? I am supporting SQL Server, mySql, SqlLite, Oracle.

**Comment by yelkarama** [comment]
SQL Server and Oracle

**Comment by yelkarama** [comment]
Hi 
Any news?
Thanks

**Comment by sheryever** [comment]
Hi,

Sql Server queries are [here](https://github.com/sheryever/simple-access-orm#using-sqlrepository-with-storedprocedure).

For Oracle, MySql, SQLite i will example in the repository
